set(_CATKIN_CURRENT_PACKAGE "vision_application_movit_config")
set(vision_application_movit_config_VERSION "0.3.0")
set(vision_application_movit_config_MAINTAINER "AAU Group 364 2021 5. semester <kasperfg16@outlook.dk>")
set(vision_application_movit_config_PACKAGE_FORMAT "1")
set(vision_application_movit_config_BUILD_DEPENDS )
set(vision_application_movit_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "ur_description")
set(vision_application_movit_config_BUILDTOOL_DEPENDS "catkin")
set(vision_application_movit_config_BUILDTOOL_EXPORT_DEPENDS )
set(vision_application_movit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "ur_description")
set(vision_application_movit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "ur_description")
set(vision_application_movit_config_TEST_DEPENDS )
set(vision_application_movit_config_DOC_DEPENDS )
set(vision_application_movit_config_URL_WEBSITE "http://moveit.ros.org/")
set(vision_application_movit_config_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(vision_application_movit_config_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(vision_application_movit_config_DEPRECATED "")