controller_list:
  - name: ur5_cam
    action_ns: scaled_pos_joint_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur5_cam_1_shoulder_pan_joint
      - ur5_cam_1_shoulder_lift_joint
      - ur5_cam_1_elbow_joint
      - ur5_cam_1_wrist_1_joint
      - ur5_cam_1_wrist_2_joint
      - ur5_cam_1_wrist_3_joint
  - name: ur5_light_bar
    action_ns: scaled_pos_joint_traj_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ur5_light_bar_1_shoulder_pan_joint
      - ur5_light_bar_1_shoulder_lift_joint
      - ur5_light_bar_1_elbow_joint
      - ur5_light_bar_1_wrist_1_joint
      - ur5_light_bar_1_wrist_2_joint
      - ur5_light_bar_1_wrist_3_joint