ur5_cam_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5_cam_1shoulder_pan_joint
    - ur5_cam_1shoulder_lift_joint
    - ur5_cam_1elbow_joint
    - ur5_cam_1wrist_1_joint
    - ur5_cam_1wrist_2_joint
    - ur5_cam_1wrist_3_joint
  gains:
    ur5_cam_1shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_cam_1shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_cam_1elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_cam_1wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_cam_1wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_cam_1wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
ur5_light_bar_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ur5_light_bar_1shoulder_pan_joint
    - ur5_light_bar_1shoulder_lift_joint
    - ur5_light_bar_1elbow_joint
    - ur5_light_bar_1wrist_1_joint
    - ur5_light_bar_1wrist_2_joint
    - ur5_light_bar_1wrist_3_joint
  gains:
    ur5_light_bar_1shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_light_bar_1shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_light_bar_1elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_light_bar_1wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_light_bar_1wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ur5_light_bar_1wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1