#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/ubuntu/p5_project_group_364/devel_isolated/ur_calibration:/home/ubuntu/p5_project_group_364/devel_isolated/ur_robot_driver:/home/ubuntu/p5_project_group_364/devel_isolated/ur_kinematics:/home/ubuntu/p5_project_group_364/devel_isolated/ur_gazebo:/home/ubuntu/p5_project_group_364/devel_isolated/ur5_cam_moveit_config:/home/ubuntu/p5_project_group_364/devel_isolated/ur_description:/home/ubuntu/p5_project_group_364/devel_isolated/ur_dashboard_msgs:/home/ubuntu/p5_project_group_364/devel_isolated/universal_robots:/home/ubuntu/p5_project_group_364/devel_isolated/controller_stopper:/home/ubuntu/p5_project/devel_isolated/vision_application_movit_config:/home/ubuntu/p5_project/devel_isolated/ur_calibration:/home/ubuntu/p5_project/devel_isolated/ur_robot_driver:/home/ubuntu/p5_project/devel_isolated/ur_kinematics:/home/ubuntu/p5_project/devel_isolated/ur_gazebo:/home/ubuntu/p5_project/devel_isolated/ur5_cam_moveit_config:/home/ubuntu/p5_project/devel_isolated/ur_description:/home/ubuntu/p5_project/devel_isolated/ur_dashboard_msgs:/home/ubuntu/p5_project/devel_isolated/universal_robots:/home/ubuntu/p5_project/devel_isolated/controller_stopper:/opt/ros/noetic:/home/ubuntu/p5_project_group_364/devel_isolated/ur_client_library:/home/ubuntu/p5_project/devel_isolated/ur_client_library'
export LD_LIBRARY_PATH='/home/ubuntu/p5_project_group_364/devel_isolated/ur_robot_driver/lib:/home/ubuntu/p5_project_group_364/devel_isolated/ur_kinematics/lib:/home/ubuntu/p5_project_group_364/devel_isolated/ur_gazebo/lib:/home/ubuntu/p5_project_group_364/devel_isolated/ur5_cam_moveit_config/lib:/home/ubuntu/p5_project_group_364/devel_isolated/ur_description/lib:/home/ubuntu/p5_project_group_364/devel_isolated/ur_dashboard_msgs/lib:/home/ubuntu/p5_project_group_364/devel_isolated/controller_stopper/lib:/home/ubuntu/p5_project/devel_isolated/vision_application_movit_config/lib:/home/ubuntu/p5_project/devel_isolated/ur_calibration/lib:/home/ubuntu/p5_project/devel_isolated/ur_robot_driver/lib:/home/ubuntu/p5_project/devel_isolated/ur_kinematics/lib:/home/ubuntu/p5_project/devel_isolated/ur_gazebo/lib:/home/ubuntu/p5_project/devel_isolated/ur5_cam_moveit_config/lib:/home/ubuntu/p5_project/devel_isolated/ur_description/lib:/home/ubuntu/p5_project/devel_isolated/ur_dashboard_msgs/lib:/home/ubuntu/p5_project/devel_isolated/controller_stopper/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu:/home/ubuntu/p5_project_group_364/devel_isolated/ur_client_library/lib:/home/ubuntu/p5_project/devel_isolated/ur_client_library/lib'
export ROSLISP_PACKAGE_DIRECTORIES="/home/ubuntu/p5_project_group_364/devel_isolated/ur_calibration/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/ubuntu/p5_project_group_364/src/Universal_Robots_ROS_Driver/ur_calibration:$ROS_PACKAGE_PATH"