#goal
string robot_name
uint8 x
uint8 y
uint8 z
uint8 rotx
uint8 roty
uint8 rotz
---
#result
string robot_name
uint8 x
uint8 y
uint8 z
uint8 rotx
uint8 roty
uint8 rotz
---
#feedback message
string robot_moved_str
